In [5]:
import json
import pandas as pd
import numpy as np

import os
import os.path
import shutil

# Leer datos

In [ ]:
#Subir un directorio
os.chdir("..")

In [41]:
#Abrir json
json_df = pd.read_json('data/places_details.json')

In [42]:
# Quedarnos con la columna que nos interesa
place_details = json_df['result']

In [73]:
# concertir en lista
places_list = []
for i in place_details:
    place_dict = dict(i)
    places_list.append(place_dict)

In [50]:
#Volver a director
os.chdir('etl')

# Crear tabla

In [145]:
df = pd.DataFrame()

for i in range(0, len(places_list)):
    temp_row = []
    try: 
        business_status = places_list[i]['business_status']
    except:
        business_status = ''
    try:    
        formatted_address = places_list[i]['formatted_address']
    except:
        formatted_address = ''
    try:
        formatted_phone_number = places_list[i]['formatted_phone_number']
    except:
        formatted_phone_number = ''
    try:
        latitude = places_list[i]['geometry']['location']['lat']
    except:
        latitude = ''
    try:
        longitude = places_list[i]['geometry']['location']['lng']
    except:
        longitude = ''
    try:
        name = places_list[i]['name']
    except:
        name = ''
    try:
        place_id = places_list[i]['place_id']
    except:
        place_id = ''
    try:
        rating = places_list[i]['rating']
    except:
        rating = ''
    try:
        user_ratings_total = places_list[i]['user_ratings_total']
    except:
        user_ratings_total = ''
    try:
        types = places_list[i]['types']
    except:
        types = ''    
    try:
        website = places_list[i]['website'] 
    except:
        website = ''
    try:
        price_level = places_list[i]['price_level']      
    except:
        price_level = float('nan')
    try:
        opening_hours = places_list[i]['opening_hours']['periods']  
    except:
        opening_hours = ''

    temp_row.append(business_status)
    temp_row.append(formatted_address)
    temp_row.append(formatted_phone_number)
    temp_row.append(latitude)
    temp_row.append(longitude)
    temp_row.append(name)
    temp_row.append(place_id)
    temp_row.append(rating)
    temp_row.append(user_ratings_total)
    temp_row.append(website)
    temp_row.append(types)
    temp_row.append(price_level)
    temp_row.append(opening_hours)
    
    df_temp = pd.DataFrame([temp_row], columns=['business_status', 'formatted_address', 'formatted_address',
                                                'latitude', 'longitude', 'name', 'place_id',
                                                'rating', 'user_ratings_total', 'website', 
                                                'types', 'price_level', 'opening_hours'
                                               ])
    df = pd.concat([df, df_temp])

In [149]:
df.to_csv('places_table.csv', index=False)

In [150]:
df

,business_status,formatted_address,formatted_address,latitude,longitude,name,place_id,rating,user_ratings_total,website,types,price_level,opening_hours
0,OPERATIONAL,"Tonalá 51, Roma Nte., Cuauhtémoc, 06700 Ciudad...",55 5511 8867,19.419040,-99.162992,Museo Muca Roma,ChIJ_49r7jn_0YURdP7aK7krgd0,4.2,286,http://www.mucaroma.unam.mx/,"[tourist_attraction, museum, point_of_interest...",NaN,"[{'close': {'day': 0, 'time': '1900'}, 'open':..."
0,OPERATIONAL,"Ahorro Postal 63, Postal, Benito Juárez, 03410...",55 1852 1252,19.388755,-99.141413,La Cocina Tradicional Mexicana,ChIJ_6PxIP_-0YURb-iv-Yq3gPM,4.5,104,https://www.facebook.com/La-Cocina-Tradicional...,"[restaurant, food, point_of_interest, establis...",NaN,"[{'close': {'day': 1, 'time': '1700'}, 'open':..."
0,OPERATIONAL,"Colegio Salesiano #61, Anáhuac I Secc, Miguel ...",55 5396 3341,19.445711,-99.177505,Santuario de Sta. María Auxiliadora,ChIJ04dL3rr40YURAM4KJYTf3F0,4.7,710,,"[church, place_of_worship, point_of_interest, ...",NaN,
0,OPERATIONAL,"Candelilla 16, Coapa, Rinconada de las Hadas, ...",55 7033 1901,19.297430,-99.120043,Candelilla 16,ChIJ06Wq3J4BzoUREnZuxiDcPo8,4.6,73,http://candelilla16.mx/,"[restaurant, food, point_of_interest, establis...",NaN,"[{'close': {'day': 6, 'time': '0000'}, 'open':..."
0,OPERATIONAL,"Calle de Tacuba 8, Centro Histórico de la Cdad...",55 8647 5430,19.436371,-99.139702,Museo Nacional De Arte (MUNAL),ChIJ0fhThCQA0oURALaHxBtFZ14,4.8,14666,http://www.munal.mx/es,"[tourist_attraction, museum, point_of_interest...",NaN,"[{'close': {'day': 0, 'time': '1700'}, 'open':..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,OPERATIONAL,"Quetzalcoatl S/N, San Bartolo Tenayuca, 54150 ...",722 215 7080,19.532086,-99.168476,Tenayuca Pyramid,ChIJ9cD_1cP30YURNsUyg6c10PA,4.3,4436,http://www.inah.gob.mx/zonas/137-zona-arqueolo...,"[tourist_attraction, museum, point_of_interest...",NaN,"[{'close': {'day': 0, 'time': '1700'}, 'open':..."
0,OPERATIONAL,"Camino a Sta. Teresa S / N, Parques del Pedreg...",55 5171 4558,19.296141,-99.193144,Tlalpan National Park,ChIJo1vaV9L_zYUR70tTSdQ2hYg,4.6,14583,http://www.bosquetlalpan.org.mx/mobile.htm,"[tourist_attraction, park, point_of_interest, ...",NaN,"[{'close': {'day': 0, 'time': '1700'}, 'open':..."
0,OPERATIONAL,"Av de Las Fuentes, Fuentes Brotantes, Tlalpan,...",,19.284438,-99.181481,Fuentes Brotantes de Tlalpan National Park,ChIJCxNtZYYAzoURIyPFhCv9XSE,4.3,4546,,"[restaurant, tourist_attraction, food, point_o...",2.0,"[{'close': {'day': 0, 'time': '1800'}, 'open':..."
0,OPERATIONAL,"Autopista México-Marquesa, Santa Fe, Contadero...",55 2591 0371,19.359167,-99.275000,El Pialadero De Guadalajara,ChIJWXCipcsA0oURjg-DI0MA-dU,4.3,633,https://elpialaderodeguadalajara.negocio.site/...,"[restaurant, food, point_of_interest, establis...",2.0,"[{'close': {'day': 0, 'time': '1900'}, 'open':..."
0,OPERATIONAL,"Hamburgo 332, Juárez, Cuauhtémoc, 06600 Cuauht...",55 5211 7708,19.421628,-99.174192,El Pialadero de Guadalajara,ChIJRU2FLk__0YURikrh-RZMung,4.3,3171,https://www.elpialaderodeguadalajara.mx/,"[restaurant, food, point_of_interest, establis...",2.0,"[{'close': {'day': 0, 'time': '1900'}, 'open':..."